In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
p=3
k=3000#迭代次数

In [3]:
np.random.seed(124)
s=p*(p-1)/2
mean=np.array([0,5,10])
#np.random.randn(p)
cov=np.zeros((p,p))

for i in range(p+1):
    for j in range(i,p):
            cov[i,j]=0.1
            cov[i,i]=1
            cov[j,i]=cov[i,j]

print("mean=",mean,"\n\nCovariance=\n",cov)

mean= [ 0  5 10] 

Covariance=
 [[1.  0.1 0.1]
 [0.1 1.  0.1]
 [0.1 0.1 1. ]]


In [4]:
eigenvalue,featurevector=np.linalg.eig(cov)
eigenvalue

array([0.9, 1.2, 0.9])

In [5]:
#交换第i个分量和第一个分量，求i的条件分布
#多元分布下求第i+1个分量的条件分布
def cond(x,mean,cov,i):#x为样本，mean为目标分布的均值，
                       #cov为目标发布的方差，i表示第i+1个分量
    t=cov
    t[[0,i],:] = t[[i,0],:] 
    t[:,[0,i]] = t[:,[i,0]]
    invt22=np.matrix(t[1:,1:]).I
    t12=np.matrix(t[0,1:])
    t21=t12.T
    a=np.dot(t12,invt22)
    b=x[1:]-mean[1:]
    meani=mean[i]+np.dot(a,b)
    c=np.dot(a,t21)
    covi=t[0,0]-c
    return meani,covi

In [6]:
sample=np.zeros((k,p))
sample[0]=[0,0,0]

In [7]:
s=cond(sample[0],mean,cov,0)
s

(matrix([[-1.36363636]]), matrix([[0.98181818]]))

In [8]:
for i in range(1,k):
    sample[i]=sample[i-1]
    for j in range(p):
        s=cond(sample[i],mean,cov,j)
        a=float(s[0])
        b=float(s[1])
        e=np.random.randn(1)
        sample[i][j]=e*np.sqrt(b)+a

In [9]:
sample[-10:]

array([[-0.07705582,  6.16351736,  8.92203541],
       [ 0.21269418,  5.25060076,  9.73956509],
       [ 0.4234657 ,  3.21743448,  9.00466566],
       [-0.78148581,  6.28626003, 10.60483076],
       [ 1.9460695 ,  4.3509062 , 12.34077332],
       [-1.15058383,  4.46320571, 11.89746059],
       [-0.50600512,  5.74239481, 10.54726627],
       [ 0.42310161,  5.2017915 ,  9.9180977 ],
       [-1.37934397,  5.48305382, 11.13499669],
       [-0.09208601,  4.01491538,  9.78463012]])

In [10]:
sample[-100:].sum(axis=0)/100

array([0.11419397, 4.91442869, 9.98342207])