In [1]:
import numpy as np

In [2]:
cc=np.zeros((20))
for i in range(20):
    cc[i]=i+1
np.random.shuffle(cc)

In [3]:
bb=[[0.        , 0.96953918],
       [0.        , 0.47148945],
       [0.        , 0.80160543],
       [0.        , 0.78629224],
       [0.        , 0.64445178],
       [0.        , 0.56762811],
       [1.        , 0.92935431],
       [1.        , 1.5428009 ],
       [1.        , 1.44315784],
       [1.        , 0.48209367]]

In [4]:
bb_dic=np.array(bb)

In [5]:
bb[9],bb[8]=bb[0],bb[9]

In [6]:
print(bb)

[[0.0, 0.96953918], [0.0, 0.47148945], [0.0, 0.80160543], [0.0, 0.78629224], [0.0, 0.64445178], [0.0, 0.56762811], [1.0, 0.92935431], [1.0, 1.5428009], [1.0, 0.48209367], [0.0, 0.96953918]]


In [7]:
#定义cc_dic，为bb的第二列
cc_dic=np.array(cc)#取bb的第二列
cc_dic1=np.array(cc)#用于测试
cc_dic

array([ 1.,  5.,  8., 20.,  6.,  7., 13., 18., 14., 11., 19., 15., 17.,
       12.,  9.,  4., 10.,  3., 16.,  2.])

In [8]:
#定义bb_dic
bb_dic=np.array(bb)
bb_dic

array([[0.        , 0.96953918],
       [0.        , 0.47148945],
       [0.        , 0.80160543],
       [0.        , 0.78629224],
       [0.        , 0.64445178],
       [0.        , 0.56762811],
       [1.        , 0.92935431],
       [1.        , 1.5428009 ],
       [1.        , 0.48209367],
       [0.        , 0.96953918]])

In [9]:
#冒泡排序
for i in range(len(cc_dic)-1):
    #需要排的位数，取n和n-1意义一样，i=k循环次数代表后k位最大的已固定
    for j in range(0,len(cc_dic)-1-i):
        # j表示每次遍历需要比较的次数，逐渐减小，比上次少1
        if cc_dic[j] > cc_dic[j+1]:
            temp = cc_dic[j+1]
            cc_dic[j+1] = cc_dic[j]
            cc_dic[j] = temp
            
cc_dic#正常排序

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [10]:
cc_dic1

array([ 1.,  5.,  8., 20.,  6.,  7., 13., 18., 14., 11., 19., 15., 17.,
       12.,  9.,  4., 10.,  3., 16.,  2.])

In [11]:
for i in range(2):
    #需要排的位数，取n和n-1意义一样(排好后)
    for j in range(len(cc_dic1)-1,i,-1):
        print("j:",j,'\t','i:',i)
        # j表示每次遍历需要比较的次数，逐渐减小，比上次少1
        if cc_dic1[j] < cc_dic1[j-1]:
            temp = cc_dic1[j-1]
            cc_dic1[j-1] = cc_dic1[j]
            cc_dic1[j] = temp
            print('\t',cc_dic1[j-1],'\t',cc_dic1[j])

print(cc,'\n',cc_dic,'\n',cc_dic1)

j: 19 	 i: 0
	 2.0 	 16.0
j: 18 	 i: 0
	 2.0 	 3.0
j: 17 	 i: 0
	 2.0 	 10.0
j: 16 	 i: 0
	 2.0 	 4.0
j: 15 	 i: 0
	 2.0 	 9.0
j: 14 	 i: 0
	 2.0 	 12.0
j: 13 	 i: 0
	 2.0 	 17.0
j: 12 	 i: 0
	 2.0 	 15.0
j: 11 	 i: 0
	 2.0 	 19.0
j: 10 	 i: 0
	 2.0 	 11.0
j: 9 	 i: 0
	 2.0 	 14.0
j: 8 	 i: 0
	 2.0 	 18.0
j: 7 	 i: 0
	 2.0 	 13.0
j: 6 	 i: 0
	 2.0 	 7.0
j: 5 	 i: 0
	 2.0 	 6.0
j: 4 	 i: 0
	 2.0 	 20.0
j: 3 	 i: 0
	 2.0 	 8.0
j: 2 	 i: 0
	 2.0 	 5.0
j: 1 	 i: 0
j: 19 	 i: 1
j: 18 	 i: 1
	 3.0 	 10.0
j: 17 	 i: 1
	 3.0 	 4.0
j: 16 	 i: 1
	 3.0 	 9.0
j: 15 	 i: 1
	 3.0 	 12.0
j: 14 	 i: 1
	 3.0 	 17.0
j: 13 	 i: 1
	 3.0 	 15.0
j: 12 	 i: 1
	 3.0 	 19.0
j: 11 	 i: 1
	 3.0 	 11.0
j: 10 	 i: 1
	 3.0 	 14.0
j: 9 	 i: 1
	 3.0 	 18.0
j: 8 	 i: 1
	 3.0 	 13.0
j: 7 	 i: 1
	 3.0 	 7.0
j: 6 	 i: 1
	 3.0 	 6.0
j: 5 	 i: 1
	 3.0 	 20.0
j: 4 	 i: 1
	 3.0 	 8.0
j: 3 	 i: 1
	 3.0 	 5.0
j: 2 	 i: 1
[ 1.  5.  8. 20.  6.  7. 13. 18. 14. 11. 19. 15. 17. 12.  9.  4. 10.  3.
 16.  2.] 
 [ 1.  2.  3.  4.  5.  

In [12]:
for i in range(5):
    for j in range(len(bb)-1,i,-1):
        # j表示每次遍历需要比较的次数，逐渐减小，比上次少1
        if bb[j][1] < bb[j-1][1]:
            bb[j],bb[j-1]=bb[j-1],bb[j]
            '''
            temp = bb_[j-1]
            bb[j-1] = bb[j]
            bb[j] = temp
            '''

bb

[[0.0, 0.47148945],
 [1.0, 0.48209367],
 [0.0, 0.56762811],
 [0.0, 0.64445178],
 [0.0, 0.78629224],
 [0.0, 0.96953918],
 [0.0, 0.80160543],
 [1.0, 0.92935431],
 [0.0, 0.96953918],
 [1.0, 1.5428009]]

In [13]:
#冒泡排序
for i in range(len(bb_dic)-1):
    for j in range(len(bb_dic)-1-i):
        # j表示每次遍历需要比较的次数，逐渐减小，比上次少1
        if bb_dic[j][1] > bb_dic[j+1][1]:
            temp = bb_dic[j+1]
            bb_dic[j+1] = bb_dic[j]
            bb_dic[j] = temp

bb_dic

array([[0.        , 0.96953918],
       [0.        , 0.96953918],
       [0.        , 0.96953918],
       [0.        , 0.96953918],
       [0.        , 0.96953918],
       [0.        , 0.96953918],
       [0.        , 0.96953918],
       [1.        , 1.5428009 ],
       [1.        , 1.5428009 ],
       [1.        , 1.5428009 ]])