In [14]:
import numpy as np
import func
import matplotlib.pyplot as plt
from sklearn.metrics.cluster import rand_score
from sklearn.metrics.cluster import adjusted_rand_score

(array([[ 0.33333333,  0.33333333,  0.33333333],
        [-2.        ,  0.        ,  2.        ],
        [ 0.5       ,  0.5       ,  0.5       ]]),
 array([0.84823459, 0.64306967, 0.61342573, 0.77565738, 0.85973448]))

In [2]:
sampleY=np.load('sampleY.npy')#sampleY[i,j]表示第i次实验第j个样本的响应变量
sampleX=np.load('sampleX.npy')#sampleX[i,j,k]表示第i次实验第j个样本的第h个分量
Betares=np.load('Betares.npy')#Betares[i]表示第i次实验的所有样本估计所得的beta
Thetares=np.load('Thetares.npy')#Thetares[i]表示第i次实验的所有样本估计所得的Theta
sgroup=np.load('sgroup.npy')#sgroup[i,j]表示第i次实验第j个样本的真实亚组

In [3]:
bias=np.zeros((1000,100))#bias[i,j]表示第i次实验第j个样本的真实值与预测值的偏差
for i in range(1000):
    bias[i]=sampleY[i]-np.dot(sampleX[i],Betares[i])

In [6]:
predgroup=np.zeros((1000,100,3))#predgroup[i,j,h]表示第i次实验第j个样本属于第h组的后验概率
for i in range(1000):
    predgroup[i]=func.Lih(bias[i],Thetares[i])

In [7]:
predclass=np.zeros((1000,100))#predclass[i,j]表示第i次实验第j个样本的预测类别
for i in range(1000):
    for j in range(100):
        predclass[i,j]=predgroup[i,j].argmax()

In [8]:
#1000次实验的每次正确率
Cratio=np.zeros((1000,100))#Cratio[i,j]表示第i次实验第j个样本是否预测正确
for i in range(1000):
    for j in range(100):
        if predclass[i,j]==sgroup[i,j]:
            Cratio[i,j]=1
cr=np.sum(Cratio,axis=1)/100

In [30]:
#1000次实验的RI index
RIindex=np.zeros(1000)
for i in range(1000):
    RIindex[i]=rand_score(sgroup[i],predclass[i])

In [31]:
RIindex

array([0.95151515, 0.93838384, 0.94888889, 0.8989899 , 0.92484848,
       0.93373737, 0.95090909, 0.93616162, 0.97414141, 0.9589899 ,
       0.97414141, 0.85616162, 0.88686869, 0.93393939, 0.83030303,
       0.85858586, 0.95151515, 0.97313131, 0.88686869, 0.94585859,
       0.93131313, 0.96606061, 0.93232323, 0.97292929, 0.84828283,
       0.88606061, 0.78484848, 0.94868687, 0.89333333, 0.92484848,
       0.94909091, 0.92040404, 0.91454545, 0.96161616, 0.88606061,
       0.98626263, 0.94909091, 0.97131313, 0.92383838, 0.94828283,
       0.88808081, 0.9210101 , 0.98626263, 0.94909091, 0.94424242,
       0.92121212, 0.90747475, 0.86787879, 0.84646465, 0.92525253,
       0.86141414, 0.93616162, 0.91636364, 0.94727273, 0.95050505,
       0.88787879, 0.91494949, 0.89575758, 0.95111111, 0.92727273,
       0.8430303 , 0.94868687, 0.91494949, 0.90666667, 0.86545455,
       0.89070707, 0.92282828, 0.90949495, 0.84464646, 0.92525253,
       0.94525253, 0.97252525, 0.91515152, 0.91939394, 0.96464

In [15]:
np.mean(Betares,axis=0)

(array([207, 213, 304, 347, 378, 386, 538, 566, 592, 606, 814, 847],
       dtype=int64),)

In [23]:
np.mean(Betares,axis=0)

array([0.84625705, 0.65001297, 0.60867761, 0.77662092, 0.85997403])

In [4]:
np.mean(Thetares,axis=0)

array([[ 0.33198038,  0.34496241,  0.32305721],
       [-1.99297462, -0.00910823,  2.03385645],
       [ 0.46004172,  0.52297983,  0.45020903]])