In [1]:
import numpy as np
import pandas as pd
import jieba
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB


In [2]:
data=pd.read_csv('out.csv')

In [3]:
data.head()

label                                             review
0      0     味道还不错，包装也不错，套餐有皮蛋瘦肉粥和老醋花生，但是送餐时间实在是有点不能忍。。。望改进
1      1                                   配送很快，服务态度很好，五星好评
2      1                                    鸽子鲜嫩，味道不错，送货及时。
3      0  請不要服務質量不一致，有時是熱的三明治，有時是冷的三明治，不要再欺騙消費者了，星巴克這種高格...
4      0               大酱汤什么玩意啊，特别少不说，里面都没有东西，一共就三块豆腐，千万别点了

In [4]:
X=data[['review']]
y=data.label

In [5]:
def cutword(text):
    return ' '.join(jieba.cut(text,use_paddle=True))

In [6]:
X['cutted_review'] = X.review.apply(cutword)

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\jieba.cache
Loading model cost 0.864 seconds.
Prefix dict has been built successfully.


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [8]:
def get_custom_stopwords(stop_words_file):
    with open(stop_words_file,encoding='UTF-8') as f:
        stopwords = f.read()
    stopwords_list = stopwords.split('\n')
    custom_stopwords_list = [i for i in stopwords_list]
    return custom_stopwords_list

In [9]:
stop_words_file = 'cn_stopwords.txt'
stopwords = get_custom_stopwords(stop_words_file)

In [10]:
'''vect = CountVectorizer()
term_matrix = pd.DataFrame(vect.fit_transform(X_train.cutted_review).toarray(), columns=vect.get_feature_names())'''


'vect = CountVectorizer()\nterm_matrix = pd.DataFrame(vect.fit_transform(X_train.cutted_review).toarray(), columns=vect.get_feature_names())'

In [11]:
'''vect = CountVectorizer(stop_words=frozenset(stopwords))
term_matrix = pd.DataFrame(vect.fit_transform(X_train.cutted_review).toarray(), columns=vect.get_feature_names())
term_matrix.head()'''

'vect = CountVectorizer(stop_words=frozenset(stopwords))\nterm_matrix = pd.DataFrame(vect.fit_transform(X_train.cutted_review).toarray(), columns=vect.get_feature_names())\nterm_matrix.head()'

In [39]:
vect1 = TfidfVectorizer()

In [40]:
term_matrix1 = pd.DataFrame(vect1.fit_transform(X_train.cutted_review).toarray(), columns=vect1.get_feature_names())

In [42]:
term_matrix1.head()

00   01   02   04   05   06   07   08   09   10  ...   默默  默默地  點的餐   鼻子  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    鼻毛   齐全   龌龊  龙利鱼  龙抄手   龟速  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 8335 columns]

In [13]:
max_df = 0.8 # 在超过这一比例的文档中出现的关键词（过于平凡），去除掉。
min_df = 5 # 在低于这一数量的文档中出现的关键词（过于独特），去除掉。
vect = TfidfVectorizer(max_df = max_df,
                       min_df = min_df,
                       token_pattern='(?u)\\b[^\\d\\W]\\w+\\b',#"(?u)“放在前面的意思是匹配中对大小写不敏感,"\b"表示匹配两个词语的间隔(可以简单的理解为空格)
                       stop_words=frozenset(stopwords))

In [15]:
'''vect1 = CountVectorizer(max_df = max_df,
                       min_df = min_df,
                       token_pattern='(?u)\\b[^\\d\\W]\\w+\\b',#"(?u)“放在前面的意思是匹配中对大小写不敏感,"\b"表示匹配两个词语的间隔(可以简单的理解为空格)
                       stop_words=frozenset(stopwords))'''

'vect1 = CountVectorizer(max_df = max_df,\n                       min_df = min_df,\n                       token_pattern=\'(?u)\\b[^\\d\\W]\\w+\\b\',#"(?u)“放在前面的意思是匹配中对大小写不敏感,"\x08"表示匹配两个词语的间隔(可以简单的理解为空格)\n                       stop_words=frozenset(stopwords))'

In [17]:
term_matrix = pd.DataFrame(vect.fit_transform(X_train.cutted_review).toarray(), columns=vect.get_feature_names())

In [18]:
term_matrix.head()

app   ok  pizza   sb   tm   一下   一个  一个半  一个多   一份  ...   麻辣  麻辣烫   麻酱  \
0  0.0  0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3  0.0  0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4  0.0  0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

   黄太吉   黄焖   黄瓜  黏糊糊  黑乎乎   黑椒   齐全  
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 1508 columns]

In [19]:
term_matrix.shape

(8990, 1508)

In [20]:
tlist=['分钟','小时','迟到','终于','三点','太慢','送到','一个半','一个多','半小时','速度慢','超时','催单','超慢','太晚','太长','好久','十点','终于','比较慢','足足','十二点','十一点','耽误','还慢','一点半','一天','钟头','这么晚','很晚','延迟','超长','八点','时段','晚点']

In [21]:
'''term_matrix[['分钟','小时','迟到','终于','三点','太慢','送到','一个半','一个多','半小时','速度慢','超时','催单','超慢','太晚','太长','好久','十点','终于','比较慢','足足','十二点','十一点','耽误','还慢','一点半','一天','钟头','这么晚','很晚','延迟','超长','八点','时段','晚点']]'''

"term_matrix[['分钟','小时','迟到','终于','三点','太慢','送到','一个半','一个多','半小时','速度慢','超时','催单','超慢','太晚','太长','好久','十点','终于','比较慢','足足','十二点','十一点','耽误','还慢','一点半','一天','钟头','这么晚','很晚','延迟','超长','八点','时段','晚点']]"

In [22]:
term_matrix.sum().sort_values().to_csv('index.csv')

In [23]:
nb = MultinomialNB()

In [24]:
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(vect, nb)

In [25]:
pipe.steps

[('tfidfvectorizer',
  TfidfVectorizer(max_df=0.8, min_df=5,
                  stop_words=frozenset({'', '$', '0', '1', '2', '3', '4', '5',
                                        '6', '7', '8', '9', '?', '_', '“', '”',
                                        '、', '。', '《', '》', '一', '一些', '一何', '一切',
                                        '一则', '一方面', '一旦', '一来', '一样', '一般', ...}),
                  token_pattern='(?u)\\b[^\\d\\W]\\w+\\b')),
 ('multinomialnb', MultinomialNB())]

In [26]:
#训练集交叉验证准确率
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train.cutted_review, y_train, cv=5, scoring='accuracy').mean()

0.846384872080089

In [27]:
pipe.fit(X_train.cutted_review, y_train)

Pipeline(steps=[('tfidfvectorizer',
                 TfidfVectorizer(max_df=0.8, min_df=5,
                                 stop_words=frozenset({'', '$', '0', '1', '2',
                                                       '3', '4', '5', '6', '7',
                                                       '8', '9', '?', '_', '“',
                                                       '”', '、', '。', '《', '》',
                                                       '一', '一些', '一何', '一切',
                                                       '一则', '一方面', '一旦', '一来',
                                                       '一样', '一般', ...}),
                                 token_pattern='(?u)\\b[^\\d\\W]\\w+\\b')),
                ('multinomialnb', MultinomialNB())])

In [28]:
pipe.predict(X_test.cutted_review)

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [29]:
y_pred = pipe.predict(X_test.cutted_review)

In [30]:
from sklearn import metrics

In [31]:
metrics.accuracy_score(y_test, y_pred)

0.8628628628628628

In [32]:
metrics.confusion_matrix(y_test, y_pred)

array([[1860,  122],
       [ 289,  726]], dtype=int64)

In [33]:
from snownlp import SnowNLP
def get_sentiment(text):
    return SnowNLP(text).sentiments

In [34]:
y_pred_snownlp = X_test.review.apply(get_sentiment)

In [35]:
y_pred_snownlp_normalized = y_pred_snownlp.apply(lambda x: 1 if x>0.5 else 0)

In [36]:
y_pred_snownlp_normalized[:5]

3259    0
1488    0
9341    0
2619    0
9799    0
Name: review, dtype: int64

In [37]:
metrics.accuracy_score(y_test, y_pred_snownlp_normalized)

0.7901234567901234

In [38]:
metrics.confusion_matrix(y_test, y_pred_snownlp_normalized)

array([[1629,  353],
       [ 276,  739]], dtype=int64)